### ISSUE TITLE
Add data-text to send text via viber, whatsup and telegram.

### ISSUE THREAD

**Issue by bvn13** [delfimov/JS-Share#2]
Please, add possibility to send text via messangers.

**Comment by delfimov** [comment]
Whatsapp, Viber and Telegram are supported since the first commit :)

**Comment by bvn13** [comment]
And what about this param?
> data-text - share description, only for vk, ok, lj, twitter, mailru, email.

**Comment by delfimov** [comment]
Oh, sorry, misread your commit. I'll need some time to investigate this. Feel free to make a merge request if you know how to do it, and I'll be happy to accept it.

**Comment by delfimov** [comment]
Added in the latest version.
