### ISSUE TITLE
Есть ли возможность добавить счетчик к кнопкам?

### ISSUE THREAD

**Issue by paveell** [delfimov/JS-Share#3]
Добрый день
Есть ли возможность добавить счетчик к кнопкам?

![screenshot__36](https://user-images.githubusercontent.com/20890143/42731543-0487c3a8-8818-11e8-89d4-656287639c67.png)

**Comment by delfimov** [comment]
Количество шар и лайков лучше собирать через бэкенд по крону, а на фронтенд отдавать закэшированные данные. Или использовать виджеты соцсетей.
